FROM python:3.12-slim

WORKDIR /app

COPY dbt/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY dbt /app/dbt

ENV DBT_PROFILES_DIR=/app/dbt
WORKDIR /app/dbt
EXPOSE 8090

CMD ["dbt", "build"]