FROM python:3.12-slim
WORKDIR /app

COPY kafka_producer/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY kafka_producer /app/kafka_producer
COPY utils /app/utils

CMD ["python", "-m", "kafka_producer.main"]