FROM python:3.12-slim

WORKDIR /app

COPY api/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY api /app/api
COPY utils /app/utils
COPY db /app/db

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]