{
 "title": "RTE-cAP",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "DATABASE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Raw events count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "orders_db",
     "rawSql": "select count(*) as value\r\nfrom raw.raw_events;\r\n"
    }
   ]
  },
  {
   "title": "Fact orders made",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "orders_db",
     "rawSql": "select count(*) as value\r\nfrom wh.fct_orders;\r\n"
    }
   ]
  },
  {
   "title": "Fact payments made",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "orders_db",
     "rawSql": "select count(*) as value\r\nfrom wh.fct_payments;\r\n"
    }
   ]
  },
  {
   "title": "Fact shipments made",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "orders_db",
     "rawSql": "select count(*) as value\r\nfrom wh.fct_shipments;\r\n"
    }
   ]
  },
  {
   "title": "Fact orders per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "orders_db",
     "rawSql": "select\r\n  date_trunc('minute', order_ts) as time,\r\n  count(*) as value\r\nfrom wh.fct_orders\r\ngroup by time\r\norder by time;\r\n"
    }
   ]
  },
  {
   "title": "Fact orders per currency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "orders_db",
     "rawSql": "select\r\n  date_trunc('minute', order_ts) as time,\r\n  currency,\r\n  count(*) as value\r\nfrom wh.fct_orders\r\ngroup by 1, 2\r\norder by 1, 2;\r\n"
    }
   ]
  },
  { "title": "PROMETHEUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Kafka brokers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_brokers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kafka topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_topics", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_db_healthy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kafka status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_kafka_healthy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Producers events/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "expr": "rate(producer_sent_total[1m])", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Consumer througput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "rate(consumer_written_total[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Orders producer errors / s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "rate(producer_errors_total{job=\"producer_orders\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Payments producer errors / s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "rate(producer_errors_total{job=\"producer_payments\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Shipments producer errors / s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "rate(producer_errors_total{job=\"producer_shipments\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "LOKI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "API ERROR logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"api\"} |= `ERROR`"
    }
   ]
  },
  {
   "title": "Consumer ERROR logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"kafka_consumer\"} |= `ERROR`"
    }
   ]
  },
  {
   "title": "Producer ERROR logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"kafka_producer\"} |= `ERROR`"
    }
   ]
  }
 ]
}