global:
  scrape_interval: 5s

scrape_configs:
  - job_name: api
    static_configs:
      - targets: ["api:8000"]

  - job_name: producer_orders
    static_configs:
      - targets: ["orders_producer:9103"]

  - job_name: producer_payments
    static_configs:
      - targets: ["payments_producer:9104"]

  - job_name: producer_shipments
    static_configs:
      - targets: ["shipments_producer:9105"]

  - job_name: consumer
    static_configs:
      - targets: ["consumer:9102"]